
#Ejercicios Numpy


In [2]:
# Ejercicio 1.
# Crea arrays de 1, 2 y 3 dimensiones. Las longitudes deben ser las siguientes, respectivamente: 6, 3 x 2 y 2 x 3 x 4

import numpy as np

In [5]:
a1 = np.random.random(6)
print(a1)

a2= np.random.random([3,2])
print(a2)

a3= np.random.random([2,3,4])
print(a3)

[0.20604426 0.50226745 0.78791839 0.03120475 0.06119887 0.43079994]
[[0.72473678 0.14429915]
 [0.04889867 0.74982456]
 [0.24469388 0.81941781]]
[[[0.85344606 0.71809257 0.56381109 0.09996367]
  [0.14574285 0.62935561 0.43208651 0.70368935]
  [0.17461246 0.59677413 0.18283593 0.45814574]]

 [[0.951578   0.98563158 0.42374734 0.77636093]
  [0.3748357  0.95954375 0.34370524 0.64735397]
  [0.88316092 0.58687364 0.5831784  0.14330814]]]


In [52]:
# Ejercicio 2.
# Crea una función que te haga un resumen estadístico básico de un array (cuartiles, mediana, media, varianza, etc) si tiene una dimensión. 
# Si tiene más de una, muestra un mensaje de alerta.

def resumen_std (array):
    if array.ndim == 1:
        resumen = {'media:':np.mean(array),
                   'mediana:':np.median(array)}
        return(resumen)

    else: 
        print("el array no tiene 2 dimensiones")
    

In [55]:
resumen1=resumen_std(a1)
resumen2=resumen_std(a2)
resumen3=resumen_std(a3)

print(resumen1)
print(resumen2)
print(resumen3)

el array no tiene 2 dimensiones
el array no tiene 2 dimensiones
{'media:': 0.3365722765067045, 'mediana:': 0.3184221000135275}
None
None


In [11]:
# Ejercicio 3.
# Crea un array de 3 dimensiones parecido al que te doy a continuación, y sin ejecutar las instrucciones siguientes, 
# intenta razonar qué números devolverán (si funcionan, claro)

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [12]:
arr[-1,-1,-1]

24

In [13]:
arr[0,1,:]

array([4, 5, 6])

In [14]:
arr[:,0,:]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [15]:
arr[:,:,-1]

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24]])

In [16]:
arr[1,2,3]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [17]:
arr[2,1,0]

16

In [18]:
arr[::2,:,:] #Todas las posiciones saltando de 2 en dos en la primera dimension

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [24]:
# Ejercicio 4.
# Crea un array de 3 x 3 que contenga valores aleatorios entre el 0 y el 100. 
# Tendrás que usar el submódulo random. 
# Una vez tengas el código, transfórmalo a una función que te permita crear arrays de tamaño N x N

b1=np.random.randint(0,100,size=(3,3))
b1

def genera_random (N):
    array_random=np.random.randint(0,100,size=(N,N))
    return array_random

genera_random(3)
genera_random(5)


array([[76, 51,  3, 54, 58],
       [22, 78, 21, 73, 21],
       [93, 49, 28,  0, 11],
       [89, 46, 69, 81, 99],
       [24, 69, 40, 97, 42]])

In [58]:
#Ejercicio 5.
#Crea una función que dependa de un número. Si la función se ejecuta con el número 5, debe devolver el siguiente array:

#1 1 1 1 1
#1 0 0 0 1
#1 0 0 0 1
#1 0 0 0 1
#1 1 1 1 1

def devuelve (n):

    if n==5:
        arr=np.ones([5,5])
        arr[1:-1, 1:-1] = np.zeros([3,3])
        #print(arr)
        return (arr)
    else:
        print("el numero es diferente de 5")


arr1=devuelve(4)
print(arr1)
arr2=devuelve(5)
print(arr2)



el numero es diferente de 5
None
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Ejercicio 6.
# Crea una función que te detecte las dimensiones de un array, y te diga cuántos datos faltantes contiene. 
# Crea unos datos de ejemplo para comprobarlo.

In [62]:
def falta (array):

    dimension = np.ndim(array)
    missing_data_count = np.isnan(array3).sum()

    return dimension, missing_data_count

array3 = np.array([[1, 2, np.nan, 7, 4, 0],[1, 2, np.nan, 7, 4, np.nan] ])
dim,missing=falta(array3)
print(dim, missing)


# Otra opcion es utilizar la funcion flatten para aplanar antes de contar
sum(np.isnan(array3.flatten()))




2 3


3

In [76]:
# Ejercicio 7.
# Crea una función que te calcule los márgenes de una tabla, es decir, la suma por columnas, la suma por filas y el total. 
# Idealmente, añadelo a la tabla original

arr = np.array( [[3,2,1,2]  ,  
                 [6,7,9,5]] )

# [3,2,1,2,8]
# [6,7,9,5,27]
# [9,9,10,7,35]

suma_columnas=(np.sum(arr, axis=0)) #suma columnas
suma_filas=(np.sum(arr, axis=1).reshape(-1,1)) #suma filas y da la vuelta
total=(np.sum(arr))

#help(np.hstack) #concatena en horizontal
#help(np.vstack) #concatena en vertical

print(suma_filas)
print(suma_columnas)
print(total)

tabla_filas = np.hstack((arr,suma_filas))
tabla_filas


[[ 8]
 [27]]
[ 9  9 10  7]
35


array([[ 3,  2,  1,  2,  8],
       [ 6,  7,  9,  5, 27]])

In [78]:
ultima_fila = np.hstack([suma_columnas, total])
ultima_fila

array([ 9,  9, 10,  7, 35])

In [80]:
tabla_margenes=np.vstack([tabla_filas, ultima_fila])
tabla_margenes

array([[ 3,  2,  1,  2,  8],
       [ 6,  7,  9,  5, 27],
       [ 9,  9, 10,  7, 35]])

In [81]:
def gen_tabla_margenes (arr):
    suma_columnas=(np.sum(arr, axis=0)) #suma columnas
    suma_filas=(np.sum(arr, axis=1).reshape(-1,1)) #suma filas y da la vuelta
    total=(np.sum(arr))
    tabla_filas = np.hstack((arr,suma_filas))
    ultima_fila = np.hstack([suma_columnas, total])
    tabla_margenes=np.vstack([tabla_filas, ultima_fila])

    return tabla_margenes


gen_tabla_margenes (arr)

array([[ 3,  2,  1,  2,  8],
       [ 6,  7,  9,  5, 27],
       [ 9,  9, 10,  7, 35]])

In [3]:
# Ejercicio 8.
# Crea una función que dados dos arrays X e Y, te calcule el coeficiente de correlación entre ellos usando la siguiente fórmula
# https://wikimedia.org/api/rest_v1/media/math/render/svg/2b9c2079a3ffc1aacd36201ea0a3fb2460dc226f

x = np.array([2,3,4,6,7,8,9,7])
y = np.array([5,6,8,5,10,8,9,5])

media_x=np.mean(x)
media_y=np.mean(y)

In [5]:
numerador = np.sum((x-media_x)*(y-media_y))
numerador

18.0

In [6]:
denominador = np.sqrt(np.sum((x-media_x)**2)) * np.sqrt(np.sum((y-media_y)**2)) 
denominador

34.8998567332303

In [7]:
corr = numerador / denominador
corr

0.5157614295551275

In [9]:
def coef_corr(x,y):

    if (x.ndim != 1 or y.ndim!=1) and (len(x)!=len(y)):
        return 'x e y deben ser de 1 dim y misma longitud'
    media_x=np.mean(x)
    media_y=np.mean(y)
    numerador = np.sum((x-media_x)*(y-media_y))
    denominador = np.sqrt(np.sum((x-media_x)**2)) * np.sqrt(np.sum((y-media_y)**2)) 

    if (denominador == 0):
        return "error, denominador 0"
    
    corr = numerador / denominador
    return corr
