# Numpy

In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [6]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a2[0]
a2[1]

array([4, 5, 6])

In [3]:
a3=np.array([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]],[[111,222,333],[444,555,666]]])
a3

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 11,  22,  33],
        [ 44,  55,  66]],

       [[111, 222, 333],
        [444, 555, 666]]])

In [11]:
a1[1]

2

In [13]:
a2[1,2]

6

In [16]:
a3[1,0,2]

33

In [19]:
av1=np.empty(4)
av1

array([4.67867386e-310, 0.00000000e+000, 4.67867447e-310, 4.67867443e-310])

In [20]:
av2=np.empty([4,3])
av2

array([[4.67867392e-310, 0.00000000e+000, 1.01855798e-312],
       [9.54898106e-313, 1.12465777e-312, 1.06099790e-312],
       [1.23075756e-312, 1.16709769e-312, 1.12465777e-312],
       [9.76118064e-313, 1.18831764e-312, 1.90979621e-312]])

In [21]:
az1=np.zeros([3,5])
az1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
ao=np.ones([3,5])
ao

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
af=np.full([3,5],9)
af

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [25]:
ai=np.identity(5)
ai

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:

np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [29]:
ar = np.arange(1,10,2)
ar

array([1, 3, 5, 7, 9])

In [30]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
          axis=0)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples

In [32]:
al=np.linspace(1,100,20)
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [33]:
aran=np.random.random([2,3])
aran

array([[0.09364822, 0.53979018, 0.00663851],
       [0.27653857, 0.12251463, 0.14019969]])

In [34]:
aran.ndim

2

In [35]:
aran.shape

(2, 3)

In [36]:
aran.size

6

In [37]:
aran.dtype

dtype('float64')

In [38]:
at=np.array(['hola','mundo'])
at

array(['hola', 'mundo'], dtype='<U5')

In [39]:
# at=np.array([['hola','mundo'],[1,2,3]]) no se pueden mezclar diferentes tipos de datos en un array

/tmp/ipykernel_11278/3172888049.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  at=np.array([['hola','mundo'],[1,2,3]])


In [40]:
al.dtype

dtype('float64')

In [45]:
al.astype('i')

array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100], dtype=int32)

In [46]:
np.sort(al)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [47]:
aran

array([[0.09364822, 0.53979018, 0.00663851],
       [0.27653857, 0.12251463, 0.14019969]])

In [49]:
np.sort(aran)

array([[0.00663851, 0.09364822, 0.53979018],
       [0.12251463, 0.14019969, 0.27653857]])

In [53]:
np.sort(aran,axis=1)

array([[0.00663851, 0.09364822, 0.53979018],
       [0.12251463, 0.14019969, 0.27653857]])

In [54]:
np.sort(aran,axis=0)

array([[0.09364822, 0.12251463, 0.00663851],
       [0.27653857, 0.53979018, 0.14019969]])

In [56]:
arr=np.array([2,4,5,0,6,15,4,1,-3])
np.min(arr)

-3

In [57]:
np.max(arr)

15

In [58]:
np.mean(arr)

3.7777777777777777

In [59]:
np.median(arr)

4.0

In [60]:
np.absolute(arr)

array([ 2,  4,  5,  0,  6, 15,  4,  1,  3])

In [61]:
np.cumsum(arr)

array([ 2,  6, 11, 11, 17, 32, 36, 37, 34])

In [62]:
np.unique(arr)

array([-3,  0,  1,  2,  4,  5,  6, 15])

In [63]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 1.48413159e+02, 1.00000000e+00,
       4.03428793e+02, 3.26901737e+06, 5.45981500e+01, 2.71828183e+00,
       4.97870684e-02])

In [64]:
np.prod(arr)

0

In [65]:
np.NaN

nan

In [66]:
for x in arr:
    print(x)

2
4
5
0
6
15
4
1
-3


In [67]:
for x in aran:
    print(x)

[0.09364822 0.53979018 0.00663851]
[0.27653857 0.12251463 0.14019969]


In [68]:
for i in range(len(arr)):
    print(i,arr[i])

0 2
1 4
2 5
3 0
4 6
5 15
6 4
7 1
8 -3


In [69]:
for x in aran:
    for y in x:
        print(y)

0.09364822489313218
0.5397901773051594
0.006638505552191365
0.27653856643598806
0.12251462607369967
0.14019969140245103


In [71]:
for x in a3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
11
22
33
44
55
66
111
222
333
444
555
666


In [72]:
np.info(np.nditer)

 nditer()

nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``copy_if_overlap`` causes the iterator to determine if read


In [73]:
for x in np.nditer(a3): #aplana el array, pierdes la posicion
    print(x)

1
2
3
4
5
6
11
22
33
44
55
66
111
222
333
444
555
666


In [74]:
np.info(np.ndenumerate) #muestra elementos y posiciones

 ndenumerate(arr)

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [76]:
for pos, x in np.ndenumerate(a3):
    print(pos,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 11
(1, 0, 1) 22
(1, 0, 2) 33
(1, 1, 0) 44
(1, 1, 1) 55
(1, 1, 2) 66
(2, 0, 0) 111
(2, 0, 1) 222
(2, 0, 2) 333
(2, 1, 0) 444
(2, 1, 1) 555
(2, 1, 2) 666


In [77]:
np.info(np.where)

 where()

where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples

In [4]:
np.where(a3>1)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 array([0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]),
 array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [11]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2=arr1.reshape([3,2,2])
print(arr2)
arro=arr2.reshape(12)
print(arro)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,1,1],[2,2,2]])
print(a*2)
print(a*b)

[[ 2  4  6]
 [ 8 10 12]]
[[ 1  2  3]
 [ 8 10 12]]


In [17]:
a=np.array([[1,2],[4,5]])
b=np.array([[1,1],[2,2]])
print(a@b)

[[ 5  5]
 [14 14]]


In [18]:
print(np.linalg.norm(a))

6.782329983125268


In [19]:
a.T

array([[1, 4],
       [2, 5]])

In [20]:
print(np.linalg.det(a))

-2.9999999999999996


In [23]:
# 1x+2y = 1
# 3x+5y = 2
a=np.array([[1,2,3],[3,5,2],[4,2,3]])
b=np.array([1,2,4])

np.linalg.solve(a,b)


array([ 1.        , -0.27272727,  0.18181818])